
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue May 08 23:32:50 CST 2018
//----------------------------------------------------

package lex;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 11;
  public static final int PUNTOYCOMA = 6;
  public static final int CADENA = 17;
  public static final int CPARENT = 5;
  public static final int IGUAL = 7;
  public static final int APOSTROFE = 3;
  public static final int UMENOS = 14;
  public static final int FLOTANTE = 15;
  public static final int ID = 18;
  public static final int POR = 12;
  public static final int EXPR = 19;
  public static final int COMA = 2;
  public static final int EOF = 0;
  public static final int DIV = 13;
  public static final int error = 1;
  public static final int ENTEROPOS = 16;
  public static final int APARENT = 4;
  public static final int KW_DATO = 8;
  public static final int WHITE_SPACE = 9;
  public static final int MAS = 10;
}

